### ISSUE TITLE
is Android included in this release?

### ISSUE THREAD

**Issue by 333337lee** [openFyde/overlay-rpi4-openfyde#5]
Hi I see Android support is on other 108 releases. I couldn't find it on my Pi 4

**Comment by Damenly** [comment]
No Android support considering the limited performance of Pi 4 at this moment.

**Comment by 333337lee** [comment]
> No Android support considering the limited performance of Pi 4 at this moment.

It works great with Fydeos

GTA San Andreas Raspberry Pi 4. The best GTA performance on Raspberry Pi.
https://youtu.be/g-UrhB4nUG4

I would like to do another video. This time with openfyde

**Comment by fydeos-alpha** [comment]
ArcHeroNG is still a WIP thing; once we believe it's ready, we will add it across the board. At the moment, it's only available in our ARM builds for the RK3588 platform.
