### ISSUE TITLE
Partition Expansion?

### ISSUE THREAD

**Issue by GrumpyMusician** [openFyde/overlay-rpi4-openfyde#7]
Hello! When flashing the openfyde image to raspberry pi, it shows up that the a lot of the storage is unallocated. How and what partitions do I expand??

**Comment by colin524** [comment]
Just expand the STATE partition using GParted

**Comment by fydeos-alpha** [comment]
Try this: https://fydeos.io/docs/knowledge-base/recipes/expand-stateful-partition
